In [8]:
import numpy as np
marks= np.array([30,56,90.8,78,67])
marks

array([30. , 56. , 90.8, 78. , 67. ])

In [5]:
marks.shape

(5,)

In [9]:
marks.dtype

dtype('float64')

In [10]:
scores = np.array([[80,90],[70,66],[55,66]])

In [11]:
scores.shape

(3, 2)

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
range_arr = np.arange(0,20,5)
range_arr

array([ 0,  5, 10, 15])

In [17]:
scores = np.array([[80,90],[60,70],[55,65]])
scores[0]

array([80, 90])

In [21]:
scores[:,0] #column first

array([80, 60, 55])

In [22]:
scores[:0]

array([], shape=(0, 2), dtype=int64)