In [27]:
import numpy as np
marks= np.array([30,56,90,78,67])
marks

array([30, 56, 90, 78, 67])

In [5]:
marks.shape

(5,)

In [9]:
marks.dtype

dtype('float64')

In [10]:
scores = np.array([[80,90],[70,66],[55,66]])

In [11]:
scores.shape

(3, 2)

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
range_arr = np.arange(0,20,5)
range_arr

array([ 0,  5, 10, 15])

In [17]:
scores = np.array([[80,90],[60,70],[55,65]])
scores[0]

array([80, 90])

In [21]:
scores[:,0] #column first

array([80, 60, 55])

In [22]:
scores[:0]

array([], shape=(0, 2), dtype=int64)

In [23]:
scores[1,1]

np.int64(70)

In [24]:
scores[scores>65]

array([80, 90, 70])

In [29]:
marks

array([30, 56, 90, 78, 67])

In [28]:
marks + 5

array([35, 61, 95, 83, 72])

In [30]:
final_marks = marks

In [31]:
midterm_marks = np.array([34,76,87,45,98])

In [33]:
avg = (midterm_marks+final_marks)/2

In [34]:
avg

array([32. , 66. , 88.5, 61.5, 82.5])

In [35]:
marks.mean()

np.float64(64.2)

In [37]:
marks.sum()

np.int64(321)

In [38]:
marks.std()

np.float64(20.49780476051033)